### ISSUE TITLE
Many tests have screenshot faliures due to missing directional light shadow

### ISSUE THREAD

**Issue by VickyAtAZ** [o3de/o3de-atom-sampleviewer#657]
Run ASV __full_test_suites__. Notice there are good amount of screenshot failures due to missing directional light shadow. 

To repro the issue,  run shadowtest.lua. 

![image](https://github.com/o3de/o3de-atom-sampleviewer/assets/55564570/abccdd99-b42f-452f-a6ae-2a354db1e736)

It may relate to these two commits:
6404925e1bf82fa2eb919ebf943b7d964d7e2dae	12/7/2023 6:03:08 AM +00:00	Add support for lighting channels
298cb5945b35fdc2d016501b5d16235536332292	11/6/2023 8:11:37 AM +00:00	Support controlling which directional light to cast shadow (#16913)

**Comment by hosea1008** [comment]
these two commits grant controls to the user to control the lighting, it might be because of the old projects doesn't have the enabling flag.

it is most likely come from 298cb5945b35fdc2d016501b5d16235536332292, for the lighting channels, the default lighting channel is set to 0 and in the shader side, it is set to accept all lighting channels by default. but for the control of directional light casting shadow, the missing value in the previous project's level.prefab might cause the problem.

**Comment by hosea1008** [comment]
I managed to reproduce the error though with a lot of shader compile fails in the asset processor of the project atom-sampleviewer, will take a look at these days.

**Comment by hosea1008** [comment]
It seems to me that the cascaded shadow is broken at some earlier point, I go back to commit 92b5dcc4ee65d3b96c8026d878ae7e0e9681334c, a commit before my first commit, I run the test and the cascaded shadow is already broken. 

I post a PR #659 to fix some of the errors related to the directional light shadow control.
